services:
  db:
    image: postgres
    restart: always
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db
    expose:
      - 5434

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
