services:
  backend:
    build: .
    ports:
      - 8082:8080
    depends_on:
      - db
    links:
      - db
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"

  db:
    image: postgres
    restart: always
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db
    volumes:
      - /var/lib/postgresql/data
    expose:
      - 5434

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
